-- FINAL SEED — NOT AUTHORIZED FOR EXECUTION
-- Additive identity: SIRI EPIP-RT 2025 / SIRI 2.1. DATEX retains the existing RTTI identity.
SELECT CASE WHEN (SELECT count(*) FROM mapping.phase3_capabilities WHERE capability_id IN (
 'CAP-DATEXII-RRP-ROAD-CLOSURE','CAP-DATEXII-RRP-LANE-CLOSURE','CAP-DATEXII-RRP-ROADWORKS',
 'CAP-DATEXII-RRP-TEMP-TRAFFIC-MGMT','CAP-DATEXII-RRP-BRIDGE-CLOSURE','CAP-DATEXII-RRP-ACCIDENT-INCIDENT',
 'CAP-DATEXII-RRP-POOR-ROAD-CONDITION','CAP-SIRI-EPIPRT-ET','CAP-SIRI-EPIPRT-SX'))=0
 THEN 'PREFLIGHT_OK' ELSE error('ABORT_CONFLICT: capability IDs exist; compare complete rows before execution') END;

INSERT INTO mapping.phase3_standards
(standard_id,standard_name,standard_kind,version,profile,service_or_subprofile,jurisdiction_context,valid_from,valid_to,source_metadata,registry_status)
VALUES ('M06-B02D-SIRI-EPIPRT-2025','SIRI','SIRI','SIRI 2.1','EPIP-RT, CEN/TS 15531-7:2025','ET and SX; exact Annex crosswalk remains partial','European',NULL,NULL,'Profile identity recorded from public preview; no deployment XSD or full element crosswalk inferred.','IDENTITY_ONLY');

INSERT INTO mapping.phase3_capabilities
(capability_id,standard_id,domain,entity,field_or_element,semantic_meaning,cardinality,required_or_optional,conditions,profile_dependency,evidence_type,limitations,review_status,fixture_kind)
VALUES
('CAP-DATEXII-RRP-ROAD-CLOSURE','M03-DATEXII-MMTIS-RRP','road disruption','road','4-SN-A Road closures','Road-closure events within RTTI 670/2022 RRP 4-SN-A.',NULL,NULL,NULL,'RTTI 670/2022; profile-specific model release unresolved','EXTERNAL_DOCUMENT','Profile category identity only; no inferred DATEX model 3.7, complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-DATEXII-RRP-LANE-CLOSURE','M03-DATEXII-MMTIS-RRP','road disruption','road lane','4-SN-B Lane closures','Lane-closure events within RTTI 670/2022 RRP 4-SN-B.',NULL,NULL,NULL,'RTTI 670/2022; profile-specific model release unresolved','EXTERNAL_DOCUMENT','Profile category identity only; no inferred DATEX model 3.7, complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-DATEXII-RRP-ROADWORKS','M03-DATEXII-MMTIS-RRP','road disruption','roadworks','4-SN-C Roadworks','Roadworks events within RTTI 670/2022 RRP 4-SN-C.',NULL,NULL,NULL,'RTTI 670/2022; profile-specific model release unresolved','EXTERNAL_DOCUMENT','Profile category identity only; no inferred DATEX model 3.7, complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-DATEXII-RRP-TEMP-TRAFFIC-MGMT','M03-DATEXII-MMTIS-RRP','road disruption','temporary traffic management','4-SN-D Temporary traffic management','Temporary traffic management measures within RTTI 670/2022 RRP 4-SN-D.',NULL,NULL,NULL,'RTTI 670/2022; profile-specific model release unresolved','EXTERNAL_DOCUMENT','Limited to temporary traffic management; no inferred model 3.7, complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-DATEXII-RRP-BRIDGE-CLOSURE','M03-DATEXII-MMTIS-RRP','road disruption','bridge','5-SN-A Bridge closures','Bridge-closure events within RTTI 670/2022 RRP 5-SN-A.',NULL,NULL,NULL,'RTTI 670/2022; profile-specific model release unresolved','EXTERNAL_DOCUMENT','Profile category identity only; no inferred DATEX model 3.7, complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-DATEXII-RRP-ACCIDENT-INCIDENT','M03-DATEXII-MMTIS-RRP','road disruption','accident or incident','5-SN-B Accidents and incidents','Accident and incident events within RTTI 670/2022 RRP 5-SN-B.',NULL,NULL,NULL,'RTTI 670/2022; profile-specific model release unresolved','EXTERNAL_DOCUMENT','Limited to this category, not all SRTI; no inferred model 3.7, complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-DATEXII-RRP-POOR-ROAD-CONDITION','M03-DATEXII-MMTIS-RRP','road disruption','road condition','5-SN-C Poor road conditions','Poor road condition events within RTTI 670/2022 RRP 5-SN-C.',NULL,NULL,NULL,'RTTI 670/2022; profile-specific model release unresolved','EXTERNAL_DOCUMENT','Profile category identity only; no inferred DATEX model 3.7, complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-SIRI-EPIPRT-ET','M06-B02D-SIRI-EPIPRT-2025','passenger service disruption','journey and call','EPIP-RT §8 Estimated Timetable (ET)','Estimated timetable service includes bounded delay and cancellation status cases.','PARTIAL',NULL,NULL,'EPIP-RT CEN/TS 15531-7:2025; SIRI 2.1','EXTERNAL_DOCUMENT','Exact Annex-to-element/constraint crosswalk remains partial; profile source is a preview; no complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL),
('CAP-SIRI-EPIPRT-SX','M06-B02D-SIRI-EPIPRT-2025','passenger service disruption','situation notice','EPIP-RT §7 Situation Exchange (SX)','Situation Exchange service includes bounded passenger disruption notices and impacts.','PARTIAL',NULL,NULL,'EPIP-RT CEN/TS 15531-7:2025; SIRI 2.1','EXTERNAL_DOCUMENT','Exact Annex-to-element/constraint crosswalk remains partial; profile source is a preview; no complete legal coverage, dataset representability, or observed implementation.','NEEDS_REVIEW',NULL);
