-- FINAL SEED — NOT AUTHORIZED FOR EXECUTION
-- Includes the missing SIRI profile identity prerequisite and 9 capability-specific sources.
-- Run only inside the approved single transaction after all dependent tables are staged.
SELECT CASE WHEN
 (SELECT count(*) FROM mapping.phase3_source_references WHERE source_reference_id IN (
 'M06-B02D-SRC-DATEX-4-SN-A','M06-B02D-SRC-DATEX-4-SN-B','M06-B02D-SRC-DATEX-4-SN-C','M06-B02D-SRC-DATEX-4-SN-D',
 'M06-B02D-SRC-DATEX-5-SN-A','M06-B02D-SRC-DATEX-5-SN-B','M06-B02D-SRC-DATEX-5-SN-C',
 'M06-B02D-SRC-SIRI-EPIPRT-ET','M06-B02D-SRC-SIRI-EPIPRT-SX'))=0
 THEN 'PREFLIGHT_OK' ELSE error('ABORT_CONFLICT: source IDs already exist; compare complete rows before execution') END;

INSERT INTO mapping.phase3_source_references
(source_reference_id,capability_id,source_kind,specification_name,version,section,url_or_document_id,retrieved_on,reviewed_on,notes,fixture_kind)
VALUES
('M06-B02D-SRC-DATEX-4-SN-A','CAP-DATEXII-RRP-ROAD-CLOSURE','OFFICIAL_PROFILE','RTTI 670/2022 Recommended Reference Profiles','RTTI 670/2022; profile-specific model release unresolved','4-SN-A Road closures','https://docs.datex2.eu/recommended-profiles/rrp/rtti/rtti-670/4-sn-a-road-closures/',DATE '2026-09-27',DATE '2026-09-27','Category/profile identity only; does not establish model release, legal coverage, dataset representability or observed implementation.',NULL),
('M06-B02D-SRC-DATEX-4-SN-B','CAP-DATEXII-RRP-LANE-CLOSURE','OFFICIAL_PROFILE','RTTI 670/2022 Recommended Reference Profiles','RTTI 670/2022; profile-specific model release unresolved','4-SN-B Lane closures','https://docs.datex2.eu/recommended-profiles/rrp/rtti/rtti-670/4-sn-b-lane-closures/',DATE '2026-09-27',DATE '2026-09-27','Category/profile identity only; does not establish model release, legal coverage, dataset representability or observed implementation.',NULL),
('M06-B02D-SRC-DATEX-4-SN-C','CAP-DATEXII-RRP-ROADWORKS','OFFICIAL_PROFILE','RTTI 670/2022 Recommended Reference Profiles','RTTI 670/2022; profile-specific model release unresolved','4-SN-C Roadworks','https://docs.datex2.eu/recommended-profiles/rrp/rtti/rtti-670/4-sn-c-roadworks/',DATE '2026-09-27',DATE '2026-09-27','Category/profile identity only; does not establish model release, legal coverage, dataset representability or observed implementation.',NULL),
('M06-B02D-SRC-DATEX-4-SN-D','CAP-DATEXII-RRP-TEMP-TRAFFIC-MGMT','OFFICIAL_PROFILE','RTTI 670/2022 Recommended Reference Profiles','RTTI 670/2022; profile-specific model release unresolved','4-SN-D Temporary traffic management','https://docs.datex2.eu/recommended-profiles/rrp/rtti/rtti-670/4-sn-d-temporary-traffic-management-measures/',DATE '2026-09-27',DATE '2026-09-27','Category/profile identity only; does not establish model release, legal coverage, dataset representability or observed implementation.',NULL),
('M06-B02D-SRC-DATEX-5-SN-A','CAP-DATEXII-RRP-BRIDGE-CLOSURE','OFFICIAL_PROFILE','RTTI 670/2022 Recommended Reference Profiles','RTTI 670/2022; profile-specific model release unresolved','5-SN-A Bridge closures','https://docs.datex2.eu/recommended-profiles/rrp/rtti/rtti-670/5-sn-a-bridge-closures/',DATE '2026-09-27',DATE '2026-09-27','Category/profile identity only; does not establish model release, legal coverage, dataset representability or observed implementation.',NULL),
('M06-B02D-SRC-DATEX-5-SN-B','CAP-DATEXII-RRP-ACCIDENT-INCIDENT','OFFICIAL_PROFILE','RTTI 670/2022 Recommended Reference Profiles','RTTI 670/2022; profile-specific model release unresolved','5-SN-B Accidents and incidents','https://docs.datex2.eu/recommended-profiles/rrp/rtti/rtti-670/5-sn-b-accidents-and-incidents/',DATE '2026-09-27',DATE '2026-09-27','Limited to this profile category; not all SRTI. No model release, legal coverage, dataset representability or observed implementation is asserted.',NULL),
('M06-B02D-SRC-DATEX-5-SN-C','CAP-DATEXII-RRP-POOR-ROAD-CONDITION','OFFICIAL_PROFILE','RTTI 670/2022 Recommended Reference Profiles','RTTI 670/2022; profile-specific model release unresolved','5-SN-C Poor road conditions','https://docs.datex2.eu/recommended-profiles/rrp/rtti/rtti-670/5-sn-c-poor-road-conditions/',DATE '2026-09-27',DATE '2026-09-27','Category/profile identity only; does not establish model release, legal coverage, dataset representability or observed implementation.',NULL),
('M06-B02D-SRC-SIRI-EPIPRT-ET','CAP-SIRI-EPIPRT-ET','OFFICIAL_PROFILE','EPIP-RT, CEN/TS 15531-7:2025','CEN/TS 15531-7:2025; SIRI 2.1','§8 Estimated Timetable (ET)','https://normy.normoff.gov.sk/norma/141185/nahlad/',DATE '2026-09-27',DATE '2026-09-27','Preview-level service identity. Exact Annex-to-element/constraint crosswalk remains partial; deployment XSD not asserted.',NULL),
('M06-B02D-SRC-SIRI-EPIPRT-SX','CAP-SIRI-EPIPRT-SX','OFFICIAL_PROFILE','EPIP-RT, CEN/TS 15531-7:2025','CEN/TS 15531-7:2025; SIRI 2.1','§7 Situation Exchange (SX)','https://normy.normoff.gov.sk/norma/141185/nahlad/',DATE '2026-09-27',DATE '2026-09-27','Preview-level service identity. Exact Annex-to-element/constraint crosswalk remains partial; deployment XSD not asserted.',NULL);
