-- Phase 3 M03: piloto de evidencia. Aditivo e idempotente; no crea mappings ni representability.
BEGIN TRANSACTION;

INSERT INTO mapping.phase3_standards
(standard_id,standard_name,standard_kind,version,profile,service_or_subprofile,jurisdiction_context,source_metadata,registry_status)
VALUES
('M03-GTFS-SCHEDULE-2026-04','General Transit Feed Specification Schedule','GTFS_SCHEDULE','Reference revision 2026-04-27','GTFS Schedule Reference',NULL,'General','Official live reference by MobilityData / GTFS project; reviewed 2026-09-27','REVIEWED'),
('M03-NETEX-EPIP-2017','Network and Timetable Exchange (NeTEx)','NETEX','CEN/TS 16614-4:2017','European Passenger Information Profile (EPIP)','Passenger information','European; national minimum profile not established','Profile identity listed by Transmodel/CEN ecosystem; public scope sources only; reviewed 2026-09-27','REVIEWED')
 ,('M03-DATEXII-MMTIS-RRP','DATEX II','DATEX_II','RRP documentation current in official v3.3 documentation','MMTIS Recommended Reference Profiles','Road traffic/travel data; MMTIS use cases','European; Spanish national profile not established','DATEX II official documentation calls these Recommended Reference Profiles; not equated with a legally mandatory EU minimum profile; reviewed 2026-09-27','IDENTITY_ONLY')
ON CONFLICT DO NOTHING;

INSERT INTO mapping.phase3_capabilities
(capability_id,standard_id,domain,entity,field_or_element,semantic_meaning,evidence_type,limitations,review_status)
VALUES
('CAP-GTFS-SCHEDULE-TRIP-STOP-TIMES','M03-GTFS-SCHEDULE-2026-04','scheduled public transport','trip, stop, route','routes.txt; trips.txt; stops.txt; stop_times.txt','GTFS Schedule Reference defines routes, trips, stops, and arrival/departure times associated with trips.','FIELD','Does not establish legal coverage of Annex point 1, historical/observed data, all modes, NAP access, or compliance.','NEEDS_REVIEW'),
('CAP-GTFS-FEED-PUBLISHER-METADATA','M03-GTFS-SCHEDULE-2026-04','dataset metadata','feed','feed_info.txt: feed_publisher_name, feed_publisher_url, feed_version','GTFS Schedule can express dataset publisher identity and URL and feed version metadata.','FIELD','Publisher is not necessarily the source of each underlying data item; does not prove an Article 8(3) request or response.','NEEDS_REVIEW'),
('CAP-GTFS-DATASET-ATTRIBUTION','M03-GTFS-SCHEDULE-2026-04','dataset attribution','dataset, agency, route, trip','attributions.txt','GTFS Schedule provides attribution records applicable at dataset, agency, route, or trip scope.','FIELD','Attribution is not necessarily the legally relevant source for each reused datum and does not prove disclosure to a user.','NEEDS_REVIEW'),
('CAP-NETEX-PT-NETWORK-TIMETABLE-EXCHANGE','M03-NETEX-EPIP-2017','public transport static data','network and timetable','CEN/TS 16614 parts 1–4; EPIP profile identity','Public CEN ecosystem material identifies NeTEx exchange for public transport network and scheduled timetable concepts, with EPIP as a named European profile.','EXTERNAL_DOCUMENT','Full normative profile detail unavailable in reviewed public sources; national minimum profile applicable under Regulation 2017/1926 Article 4(2) remains unknown.','NEEDS_REVIEW')
 ,('CAP-DATEXII-RRP-ROAD-TRAVEL','M03-DATEXII-MMTIS-RRP','road traffic and travel data','road link travel times; MMTIS use cases','MMTIS RRP documentation; specific profiles include current and future predicted road link travel times','Official DATEX II documentation describes RRP as use-case subsets and identifies MMTIS profiles; this establishes technical profile families, not applicability to each Annex point-1 element.','EXTERNAL_DOCUMENT','MMTIS page also lists categories from prior/other regulatory contexts; some are dynamic point-2 data or changed by Regulation 2024/490. No point-1 assignment or Spanish national profile is inferred.','NEEDS_REVIEW')
ON CONFLICT DO NOTHING;

INSERT INTO mapping.phase3_source_references
(source_reference_id,capability_id,source_kind,specification_name,version,section,url_or_document_id,retrieved_on,reviewed_on,notes)
VALUES
('M03-SRC-GTFS-TRIP-STOP','CAP-GTFS-SCHEDULE-TRIP-STOP-TIMES','OFFICIAL_SPECIFICATION','GTFS Schedule Reference','Revision 2026-04-27','Dataset Files; routes.txt; trips.txt; stops.txt; stop_times.txt','https://gtfs.org/documentation/schedule/reference/',DATE '2026-09-27',DATE '2026-09-27','Official MobilityData/GTFS reference; static schedule field definitions. Does not establish legal coverage.'),
('M03-SRC-GTFS-FEED-INFO','CAP-GTFS-FEED-PUBLISHER-METADATA','OFFICIAL_SPECIFICATION','GTFS Schedule Reference','Revision 2026-04-27','feed_info.txt','https://gtfs.org/documentation/schedule/reference/',DATE '2026-09-27',DATE '2026-09-27','Publisher metadata, not necessarily provenance of each data item.'),
('M03-SRC-GTFS-ATTRIBUTION','CAP-GTFS-DATASET-ATTRIBUTION','OFFICIAL_SPECIFICATION','GTFS Schedule Reference','Revision 2026-04-27','attributions.txt','https://gtfs.org/documentation/schedule/reference/',DATE '2026-09-27',DATE '2026-09-27','Attribution scope can be dataset, agency, route, or trip; legal source disclosure not inferred.'),
('M03-SRC-NETEX-CEN-SCOPE','CAP-NETEX-PT-NETWORK-TIMETABLE-EXCHANGE','OFFICIAL_PROFILE','NeTEx extension for New Modes — Detailed Scope','2021 public scope document','pp. 2–3: profiles and European Profile; pp. 4–5: public transport concepts','https://www.netex-cen.eu/wp-content/uploads/2021/04/NeTEx-extension-for-New-Modes-Detailed-Scope.pdf',DATE '2026-09-27',DATE '2026-09-27','Public scope document, not normative EPIP text.'),
('M03-SRC-NETEX-EPIP-INDEX','CAP-NETEX-PT-NETWORK-TIMETABLE-EXCHANGE','OFFICIAL_PROFILE','Standards for implementation — Transmodel','CEN/TS 16614-4:2017','NeTEx Profiles: Part 4 European Passenger Information Profile; implementation standards table','https://transmodel-cen.eu/index.php/standards-for-implementation/',DATE '2026-09-27',DATE '2026-09-27','Official ecosystem index supports profile identity only, not full normative semantics or national applicability.')
 ,('M03-SRC-DATEXII-MMTIS-RRP','CAP-DATEXII-RRP-ROAD-TRAVEL','OFFICIAL_PROFILE','Recommended Reference Profiles - MMTIS','Official DATEX II RRP documentation; v3.3 context where linked','MMTIS overview, profile role and data categories; official profile documentation linked from overview','https://docs.datex2.eu/recommended-profiles/rrp/mmtis/',DATE '2026-09-27',DATE '2026-09-27','Terminology preserved as Recommended Reference Profiles. Overview describes minimum data elements per datacategory; this is not legal designation as EU minimum profile and does not prove Article 4(2) point-1 applicability.')
 ,('M03-SRC-DATEXII-TRAVELTIME','CAP-DATEXII-RRP-ROAD-TRAVEL','OFFICIAL_PROFILE','Road Link traveltime - DATEX II Docs','Official MMTIS RRP documentation','RRP scope for current road-link travel times; profile elements and scope','https://docs.datex2.eu/recommended-profiles/rrp/mmtis/ls2a-current-road-link-travel-times/',DATE '2026-09-27',DATE '2026-09-27','Road-specific technical profile; no legal Annex point-1 mapping inferred.')
ON CONFLICT DO NOTHING;

INSERT INTO mapping.phase3_exceptions
(exception_id,requirement_id,exception_type,reason,justification,evidence_expectations,review_status)
VALUES
('M03-EXC-A05-DEADLINE','EU-2017-1926-REQ-A05-P03-001','DEADLINE','Legal deadline and geographic applicability are not transport-format fields.','The frozen requirement is the 2025-12-01 deadline for Annex point 2.1 data on the comprehensive TEN-T network. Calendar/feed date fields cannot establish timely legal provision.','Applicable data/geography determination; dated NAP publication/access records; evidence supporting availability by the legal deadline.','NEEDS_REVIEW'),
('M03-EXC-A08-SOURCE-REQUEST','EU-2017-1926-REQ-A08-P03-001-01','EXTERNAL_EVIDENCE','The duty is conditional on reuse and a data holder request; technical publisher/attribution metadata alone does not prove the source disclosure or response.','GTFS fields support only bounded dataset publisher/attribution capabilities; request handling and source provenance require external documentary evidence.','Reuse context; request record; provenance of the reused data; response/disclosure record linked to the request.','NEEDS_REVIEW'),
('M03-EXC-A09-RANDOM-CHECKS','EU-2017-1926-REQ-A09-P03-RANDOM_CHECKS','MANUAL_ASSESSMENT','Random accuracy checks are an institutional supervisory act, not a capability of a transport exchange format.','The frozen duty assigns checks to Member States and concerns accuracy of Article 9(2)(c) declarations; this pilot supplies no method, frequency, or sample size.','Authority/process records; sampled declarations and corroborating evidence; documented check outcome and method where established.','NEEDS_REVIEW')
ON CONFLICT DO NOTHING;

COMMIT;
