-- M06-B02A: persist only the seven human-authorized requirement concepts.
-- Idempotent insert-only seed; any existing ID/code with different fields aborts.
BEGIN TRANSACTION;

CREATE TEMP TABLE b02a_seed AS
SELECT * FROM (VALUES
 ('M06-B02-CPT-A05-P01-002-ROAD-STATUS-DISRUPTION','EU-2017-1926-REQ-A05-P01-002','ROAD_STATUS_DISRUPTION','Road status and disruption','Dynamic road-network status and disruption within the bounded road-status concept. It does not cover all dynamic road data or travel-time concepts.','PARTIAL',NULL,'EU-2017-1926-SF-A05-P01-ROAD; M06_B02_HUMAN_REVIEW.md C01; M06_B02_POST_HUMAN_REVIEW.md; human decision ACCEPT_WITH_LIMITATIONS. Legal/source basis: Article 5(1)(a), consolidated 2024-03-04. Future technical mapping basis is separate and excluded from this concept definition.','APPROVED','ACCEPTED_WITH_LIMITATIONS','Human decision on C01 accepts a bounded road-status concept; exact profile and legal successor linkage remain limitations.','Exact applicable category/profile and version are not fixed. The 2015/962 source citation remains literal; current RTTI context is not a legal substitution.',TIMESTAMP '2026-09-28 00:00:00','Yeison Arbey Carrillo Lemus',DATE '2026-09-28','Yeison Arbey Carrillo Lemus','M06-B02A authorized concept persistence; functional/legal concept only.'),
 ('M06-B02-CPT-A05-P02-001-ROAD-STATUS-DISRUPTION','EU-2017-1926-REQ-A05-P02-001','ROAD_STATUS_DISRUPTION','Road status and disruption','Road disruption/status within relevant Annex 2.1 road branches, limited to the conditional scope of this requirement.','PARTIAL','Applies only where Article 5(2) makes the named profile applicable.','EU-2017-1926-SF-A05-P02; M06_B02_HUMAN_REVIEW.md C04; M06_B02_POST_HUMAN_REVIEW.md; human decision ACCEPT_WITH_LIMITATIONS. Legal/source basis: Article 5(2), consolidated 2024-03-04. Future technical mapping basis is separate and excluded from this concept definition.','APPROVED','ACCEPTED_WITH_LIMITATIONS','Human decision on C04 accepts a bounded road-status concept under the conditional requirement.','Does not cover all Annex 2.1/2.2 categories; exact applicable category/profile and version remain open.',TIMESTAMP '2026-09-28 00:00:00','Yeison Arbey Carrillo Lemus',DATE '2026-09-28','Yeison Arbey Carrillo Lemus','M06-B02A authorized concept persistence; functional/legal concept only.'),
 ('M06-B02-CPT-A05-P02-001-PASSENGER-RT-STATUS-DISRUPTION','EU-2017-1926-REQ-A05-P02-001','PASSENGER_RT_STATUS_DISRUPTION','Passenger real-time service status and disruption','Real-time status of public passenger services, including delay, cancellation and disruption information within the human-reviewed concept scope.','PARTIAL','Applies only where Article 5(2) makes the named profile applicable.','EU-2017-1926-SF-A05-P02; M06_B02_HUMAN_REVIEW.md C07; M06_B02_POST_HUMAN_REVIEW.md; human decision ACCEPT_WITH_LIMITATIONS. Legal/source basis: Article 5(2), consolidated 2024-03-04. Future technical mapping basis is separate and excluded from this concept definition.','APPROVED','ACCEPTED_WITH_LIMITATIONS','Human decision on C07 accepts the bounded passenger real-time status concept.','Does not establish every mode, Annex element, profile or all P02 scope.',TIMESTAMP '2026-09-28 00:00:00','Yeison Arbey Carrillo Lemus',DATE '2026-09-28','Yeison Arbey Carrillo Lemus','M06-B02A authorized concept persistence; profile versions are not part of concept identity.'),
 ('M06-B02-CPT-A05-P02-001-FACILITY-ACCESS-NODE-STATUS','EU-2017-1926-REQ-A05-P02-001','FACILITY_ACCESS_NODE_STATUS','Facility and access-node status','Status of availability of access facilities at a transport node, such as lifts or escalators when the reviewed item applies.','PARTIAL','Applies only where Article 5(2) makes the named profile applicable.','EU-2017-1926-SF-A05-P02; M06_B02_HUMAN_REVIEW.md C08; M06_B02_POST_HUMAN_REVIEW.md; human decision ACCEPT_WITH_LIMITATIONS. Legal/source basis: Article 5(2), consolidated 2024-03-04. Future technical mapping basis is separate and excluded from this concept definition.','APPROVED','ACCEPTED_WITH_LIMITATIONS','Human decision on C08 accepts the bounded facility/access-node concept.','The Annex-item to service-element crosswalk is incomplete; no complete facility coverage is implied.',TIMESTAMP '2026-09-28 00:00:00','Yeison Arbey Carrillo Lemus',DATE '2026-09-28','Yeison Arbey Carrillo Lemus','M06-B02A authorized concept persistence; profile-specific terminology is excluded from identity.'),
 ('M06-B02-CPT-A05-P02-001-PARKING-TARIFF','EU-2017-1926-REQ-A05-P02-001','PARKING_TARIFF','Parking tariff information','Parking tariff information within the reviewed Annex 2.2(a) candidate scope.','PARTIAL','Applies only where Article 5(2) makes the named profile applicable.','EU-2017-1926-SF-A05-P02; M06_B02_POST_HUMAN_REVIEW.md U01; human decision PARTIAL. Legal/source basis: Article 5(2), consolidated 2024-03-04. No technical source is used as primary concept basis.','REVIEWED',NULL,'Human-reviewed state is PARTIAL; no ACCEPTED/REJECTED outcome was assigned.','Exact general-parking profile/version/elements and applicability chain are not established; no capability or mapping is authorized.',TIMESTAMP '2026-09-28 00:00:00','Yeison Arbey Carrillo Lemus',DATE '2026-09-28','Yeison Arbey Carrillo Lemus','Concept state PARTIAL records incomplete scope research, not absence of data.'),
 ('M06-B02-CPT-A05-P02-001-SHARED-VEHICLE-AVAILABILITY','EU-2017-1926-REQ-A05-P02-001','SHARED_VEHICLE_AVAILABILITY','Shared-vehicle availability','Availability/location of shared vehicles, preserving distinctions among vehicle modes and categories.','UNRESOLVED','Applies only where Article 5(2) makes the named profile applicable.','EU-2017-1926-SF-A05-P02; M06_B02_POST_HUMAN_REVIEW.md U02; human decision KEEP_UNRESOLVED. Legal/source basis: Article 5(2), consolidated 2024-03-04. No technical source is used as primary concept basis.','REVIEWED','UNRESOLVED','Human decision keeps the concept unresolved; no common profile/category crosswalk was established.','Requires future mode/category decomposition; no capability or mapping is authorized.',TIMESTAMP '2026-09-28 00:00:00','Yeison Arbey Carrillo Lemus',DATE '2026-09-28','Yeison Arbey Carrillo Lemus','UNRESOLVED is a concept state, not evidence of missing data or audit result.'),
 ('M06-B02-CPT-A05-P02-001-PARKING-AVAILABILITY','EU-2017-1926-REQ-A05-P02-001','PARKING_AVAILABILITY','Parking-space availability','Availability of parking spaces, without asserting a common treatment for on-street and off-street parking.','PARTIAL','Applies only where Article 5(2) makes the named profile applicable.','EU-2017-1926-SF-A05-P02; M06_B02_POST_HUMAN_REVIEW.md U03; human decision PARTIAL. Legal/source basis: Article 5(2), consolidated 2024-03-04. No technical source is used as primary concept basis.','REVIEWED',NULL,'Human-reviewed state is PARTIAL; no ACCEPTED/REJECTED outcome was assigned.','Exact profile/version/elements and on/off-street applicability remain unresolved; no capability or mapping is authorized.',TIMESTAMP '2026-09-28 00:00:00','Yeison Arbey Carrillo Lemus',DATE '2026-09-28','Yeison Arbey Carrillo Lemus','Concept state PARTIAL records incomplete scope research, not absence of data.')
) AS t(concept_id,requirement_id,concept_code,concept_name,concept_description,scope_status,applicability_conditions,source_basis,review_status,review_outcome,review_justification,limitations,created_at,created_by,reviewed_at,reviewed_by,notes);

SELECT CASE WHEN (SELECT count(*) FROM b02a_seed)=7 AND
 (SELECT count(*) FROM compliance.requirements WHERE requirement_id IN (SELECT requirement_id FROM b02a_seed))=2 AND
 (SELECT count(*) FROM (
   SELECT concept_id,requirement_id,concept_code,concept_name,concept_description,scope_status,applicability_conditions,source_basis,review_status,review_outcome,review_justification,limitations,created_at,created_by,reviewed_at,reviewed_by,notes
   FROM mapping.phase3_requirement_concepts WHERE concept_id IN (SELECT concept_id FROM b02a_seed)
   EXCEPT ALL SELECT * FROM b02a_seed))=0 AND
 (SELECT count(*) FROM mapping.phase3_requirement_concepts WHERE requirement_id IN (SELECT requirement_id FROM b02a_seed) AND concept_code IN (SELECT concept_code FROM b02a_seed))= (SELECT count(*) FROM mapping.phase3_requirement_concepts WHERE concept_id IN (SELECT concept_id FROM b02a_seed))
THEN 'M06B02A_CONFLICT_CHECK_PASS' ELSE error('M06-B02A conflicting ID or requirement/code uniqueness; aborted') END;

INSERT INTO mapping.phase3_requirement_concepts
SELECT * FROM b02a_seed s WHERE NOT EXISTS (SELECT 1 FROM mapping.phase3_requirement_concepts c WHERE c.concept_id=s.concept_id);

SELECT CASE WHEN
 (SELECT count(*) FROM mapping.phase3_requirement_concepts WHERE concept_id IN (SELECT concept_id FROM b02a_seed))=7 AND
 (SELECT count(*) FROM mapping.phase3_concept_mappings WHERE concept_id IN (SELECT concept_id FROM b02a_seed))=0 AND
 (SELECT count(*) FROM mapping.phase3_requirement_capabilities WHERE requirement_id IN (SELECT requirement_id FROM b02a_seed))=0 AND
 (SELECT count(*) FROM mapping.phase3_requirement_coverage WHERE requirement_id IN (SELECT requirement_id FROM b02a_seed))=0 AND
 (SELECT count(*) FROM mapping.phase3_representability WHERE fixture_kind IS DISTINCT FROM 'SYNTHETIC_TEST')=0 AND
 (SELECT count(*) FROM mapping.phase3_observed_evidence WHERE fixture_kind IS DISTINCT FROM 'SYNTHETIC_TEST')=0 AND
 (SELECT count(*) FROM audit.rules)=0
THEN 'M06B02A_POSTCHECK_PASS' ELSE error('M06-B02A postcheck failed; transaction rolled back') END;
COMMIT;
