-- FINAL SEED — NOT AUTHORIZED FOR EXECUTION
SELECT CASE WHEN (SELECT count(*) FROM mapping.phase3_mapping_reviews WHERE mapping_id LIKE 'M06-B02-MAP-A05-%')=0
 THEN 'PREFLIGHT_OK' ELSE error('ABORT_CONFLICT: B02 reviews exist; compare complete rows before execution') END;
INSERT INTO mapping.phase3_mapping_reviews(mapping_id,semantic_review_outcome,justification,limitations,reviewed_by,reviewed_at)
VALUES
('M06-B02-MAP-A05-P01-002-DATEX-4-SN-A','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C01 to the road-closure category 4-SN-A.','Profile-specific DATEX model release unresolved; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P01-002-DATEX-4-SN-B','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C01 to the lane-closure category 4-SN-B.','Profile-specific DATEX model release unresolved; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P01-002-DATEX-4-SN-C','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C01 to the roadworks category 4-SN-C.','Profile-specific DATEX model release unresolved; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P01-002-DATEX-4-SN-D','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C01 to the temporary traffic management category 4-SN-D.','Profile-specific DATEX model release unresolved; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P01-002-DATEX-5-SN-A','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C01 to the bridge-closure category 5-SN-A.','Profile-specific DATEX model release unresolved; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P01-002-DATEX-5-SN-B','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C01 to the accidents/incidents category 5-SN-B.','Limited to this category and not all SRTI; profile-specific model release unresolved; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P01-002-DATEX-5-SN-C','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C01 to the poor-road-conditions category 5-SN-C.','Profile-specific DATEX model release unresolved; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P02-001-SIRI-ET','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C07 to EPIP-RT Estimated Timetable (ET), limited to journey delay and cancellation.','EPIP-RT is CEN/TS 15531-7:2025 over SIRI 2.1; exact Annex-to-element/constraint crosswalk remains partial; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28'),
('M06-B02-MAP-A05-P02-001-SIRI-SX','ACCEPTED_WITH_LIMITATIONS','Human-approved partial relation of C07 to EPIP-RT Situation Exchange (SX), limited to passenger disruption notices.','EPIP-RT is CEN/TS 15531-7:2025 over SIRI 2.1; exact Annex-to-element/constraint crosswalk remains partial; no complete requirement coverage, dataset representability, observed implementation, or legal-compliance conclusion.','Yeison Arbey Carrillo Lemus',DATE '2026-09-28');
